SEGMENT_PAGES = {
    'workmarket-contractors': {
        'eyebrow': 'For WorkMarket contractors',
        'title': 'Keep WorkMarket jobs, crew assignments, and invoices in one operating view',
        'description': 'FieldBase helps small field-service crews schedule accepted work, catch overlaps, dispatch technicians, and move completed jobs into invoicing.',
        'problem': 'A platform inbox can tell you about an assignment. It does not run the rest of your crew’s day across direct jobs, calls, and other work sources.',
        'outcomes': [
            'See WorkMarket and non-platform jobs on the same calendar.',
            'Catch overlapping assignments before they become missed appointments.',
            'Give technicians a focused mobile workflow without exposing full job value.',
            'Close completed work and create a client payment path from the same record.',
        ],
        'boundary': 'WorkMarket synchronization requires valid WorkMarket API access. Manual, screenshot, and voice entry remain available when an API connection is unavailable.',
        'source': 'workmarket',
    },
    'field-nation-contractors': {
        'eyebrow': 'For Field Nation contractors',
        'title': 'Run Field Nation work alongside every direct job your crew accepts',
        'description': 'FieldBase gives small field-service operators one schedule for marketplace work, direct clients, technicians, field status, and invoices.',
        'problem': 'When assignments live in one marketplace and crew coordination lives in texts or paper, conflicts and unbilled work become easy to miss.',
        'outcomes': [
            'Bring marketplace and direct work into one job calendar.',
            'Assign the right technician and track confirmation through completion.',
            'Keep job photos, documents, notes, and payout status together.',
            'Move owner-approved completed work into invoicing without re-entering it.',
        ],
        'boundary': 'Field Nation synchronization requires valid Field Nation API access. Manual, screenshot, and voice entry remain available when an API connection is unavailable.',
        'source': 'fieldnation',
    },
    'low-voltage-contractors': {
        'eyebrow': 'For low-voltage crews',
        'title': 'Schedule cabling, network, camera, and service calls without the spreadsheet shuffle',
        'description': 'FieldBase connects dispatch, technician execution, job documentation, and invoicing for small low-voltage teams.',
        'problem': 'Low-voltage work mixes scheduled installs, urgent service calls, changing scopes, site photos, and subcontractor coordination.',
        'outcomes': [
            'Keep install and break-fix work visible on one calendar.',
            'Store scope, site details, photos, and technician notes with the job.',
            'Track technician confirmation, arrival, work, and owner review.',
            'Create a payment link when approved work is complete.',
        ],
        'boundary': 'FieldBase supports workflow and documentation; it does not replace site safety procedures, licensing requirements, or client acceptance rules.',
        'source': 'low_voltage',
    },
    'it-field-service': {
        'eyebrow': 'For IT field-service crews',
        'title': 'Turn scattered break-fix dispatches into a visible job-to-payment workflow',
        'description': 'FieldBase helps small IT field-service operators coordinate technicians, capture field proof, and keep completed work from waiting on paperwork.',
        'problem': 'Dispatch details arrive through marketplace portals, email, screenshots, and calls while technicians need one clear mobile view.',
        'outcomes': [
            'Capture job details from a form, screenshot, or voice note.',
            'Assign technicians while keeping owner financials private.',
            'Collect timestamps, notes, photos, and documents on the job.',
            'Review completed work and send the invoice from the owner dashboard.',
        ],
        'boundary': 'AI-assisted extraction should be reviewed before saving. Availability depends on configured provider services.',
        'source': 'it_field_service',
    },
    'security-camera-installers': {
        'eyebrow': 'For security and camera installers',
        'title': 'Keep surveys, installs, service calls, field proof, and billing tied together',
        'description': 'FieldBase gives small camera and security crews a practical schedule-to-invoice workflow built around real field jobs.',
        'problem': 'A single job can involve changing site details, technician assignments, before-and-after photos, and client documentation.',
        'outcomes': [
            'Schedule surveys, installations, and service calls together.',
            'Attach site documents and photos to the correct job.',
            'Track field progress without a separate status spreadsheet.',
            'Move reviewed work into invoice and payment tracking.',
        ],
        'boundary': 'FieldBase records operations; it does not provide alarm monitoring, video storage, or code-compliance certification.',
        'source': 'security_cameras',
    },
    'pos-installers': {
        'eyebrow': 'For POS installers',
        'title': 'Coordinate multi-site POS work without losing the dispatch details',
        'description': 'FieldBase keeps locations, technicians, schedules, completion notes, and billing in one place for small POS service crews.',
        'problem': 'Multi-site rollouts and break-fix calls create repetitive dispatch work where one missed time, address, or closeout can erase margin.',
        'outcomes': [
            'Schedule location-specific work with clear start and end times.',
            'Assign technicians and monitor confirmation and field status.',
            'Capture closeout notes, photos, and documents.',
            'Track which completed jobs have been invoiced and paid.',
        ],
        'boundary': 'FieldBase does not replace customer ticketing systems; it provides the crew operating layer around accepted work.',
        'source': 'pos',
    },
}


GUIDES = {
    'field-service-invoicing': {
        'eyebrow': 'Field-service operations guide',
        'title': 'A practical completed-job-to-invoice checklist',
        'description': 'A repeatable closeout sequence for small field-service crews that want less missing paperwork and faster invoicing.',
        'steps': [
            ('Confirm the work is actually complete', 'Require technician status, completion notes, and any client-required evidence before the owner closes the job.'),
            ('Check the billable amount', 'Compare the accepted work order, approved changes, labor, materials, and travel before generating the invoice.'),
            ('Keep proof with the job', 'Attach before-and-after photos, sign-off documents, and technician notes to the same record.'),
            ('Verify the billing contact', 'Confirm the client name, company, email, payment terms, and any purchase-order requirement.'),
            ('Send one clear payment path', 'Include the job reference, amount due, due date, and a secure card-payment option when appropriate.'),
            ('Reconcile payment status', 'Do not treat an invoice as paid until the payment provider or bank confirms it.'),
        ],
        'cta': 'Put the checklist into one job workflow',
        'source': 'invoice_guide',
    },
    'prevent-double-booking-field-technicians': {
        'eyebrow': 'Field-service scheduling guide',
        'title': 'How small crews prevent technician double-booking',
        'description': 'A simple scheduling control for owners accepting jobs from marketplaces, direct clients, email, and phone.',
        'steps': [
            ('Use one source of schedule truth', 'Every accepted job must reach the same calendar, regardless of where it originated.'),
            ('Store real start and end times', 'A start time without expected duration hides overlaps and travel constraints.'),
            ('Assign a named technician', 'Unassigned work is not capacity planning. Assign ownership before confirming coverage.'),
            ('Check overlap before acceptance', 'Compare the candidate time window against every scheduled job for that technician.'),
            ('Account for travel and site access', 'Back-to-back jobs can still conflict when distance, parking, escorts, or check-in add time.'),
            ('Require confirmation', 'Treat an unconfirmed assignment as a risk until the technician acknowledges it.'),
        ],
        'cta': 'See conflicts in the same calendar as your jobs',
        'source': 'conflict_guide',
    },
}
